import { CONFIG } from '../config';

export const metadata = {
  title: 'Privacy Policy - ' + CONFIG.siteName,
  description: 'Read our Privacy Policy. We prioritize your anonymity. No logs, no tracking, and complete data erasure.',
};

export default function PrivacyPage() {
  return (
    <div className="container-main">
      
      {/* JUDUL HALAMAN (Saya samakan style-nya dengan Home) */}
      <div className="hero-text" style={{ padding: '30px 10px', textAlign: 'center' }}>
        <h1 style={{ fontSize: '28px', fontWeight: 'bold', marginBottom: '10px', marginTop: 0 }}>Privacy Policy</h1>
        <p style={{ color: '#777', fontSize: '14px' }}>Last Updated: {new Date().getFullYear()}</p>
      </div>

      {/* KONTEN ARTIKEL (Style disamakan PERSIS dengan Home) */}
      <div className="seo-content-final" style={{ 
          marginBottom: '80px', 
          textAlign: 'left',
          padding: '0 10px', // <--- INI KUNCINYA (Disamakan jadi 10px biar lebar)
          color: '#555',
          lineHeight: '1.7', // Disamakan dengan Home
          fontSize: '15px'   // Ukuran font standar yang pas di HP
      }}>

        <p style={{ marginBottom: '25px' }}>
          At <strong>{CONFIG.siteName}</strong>, accessible from <strong>{CONFIG.dom}</strong>, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by <strong>{CONFIG.siteName}</strong> and how we use it. We are fundamentally committed to protecting your digital anonymity. Unlike traditional email services that require extensive personal data, our core service is designed to function with absolute minimalism regarding user data. This policy outlines our staunch commitment to "No Logs" and data erasure practices.
        </p>

        <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: '#333', marginTop: '30px', marginBottom: '10px' }}>
          General Consent and Scope
        </h3>
        <p style={{ marginBottom: '25px' }}>
          By using our website, you hereby consent to our Privacy Policy and agree to its terms. This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in <strong>{CONFIG.siteName}</strong>. This policy is not applicable to any information collected offline or via channels other than this website. We operate globally, and as such, we adhere to general data protection principles that prioritize the user's right to be forgotten and the right to anonymity.
        </p>

        <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: '#333', marginTop: '30px', marginBottom: '10px' }}>
          The Philosophy of "No Logs"
        </h3>
        <p style={{ marginBottom: '25px' }}>
          We strictly adhere to a no-logs policy. This means we do not store your IP address, your browser User-Agent, your location data, or your usage duration in any permanent database. Most web servers automatically maintain log files that record every request made to the server. However, our infrastructure is configured to discard these logs periodically or not write them at all. Our goal is to ensure that even if our servers were physically seized by a third party, there would be no historical data connecting a specific user to a specific temporary email address. Your anonymity is baked into our system architecture, not just our legal promises.
        </p>

        <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: '#333', marginTop: '30px', marginBottom: '10px' }}>
          Collection and Use of Temporary Emails
        </h3>
        <p style={{ marginBottom: '25px' }}>
          The primary function of <strong>{CONFIG.siteName}</strong> is to receive emails on behalf of a temporary identity. When an email is sent to an address generated by our system, that email is processed by our mail servers. The content of these emails is stored in temporary storage (RAM or ephemeral database tables) solely for the purpose of displaying it to you in the browser. We do not analyze the content of your emails for advertising purposes. We do not scan your messages to build a profile of your interests. Furthermore, we have automated cron jobs (scheduled tasks) that permanently delete all email messages and the temporary email addresses themselves after a short period, typically ranging from 10 minutes to a few hours depending on system load. Once deleted, this data is irretrievable.
        </p>

        <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: '#333', marginTop: '30px', marginBottom: '10px' }}>
          Cookies and Web Beacons
        </h3>
        <p style={{ marginBottom: '25px' }}>
          Like any other website, <strong>{CONFIG.siteName}</strong> uses 'cookies'. However, our use of cookies is strictly minimal and essential for the functionality of the service. We use cookies to maintain your session so that when you refresh the page, you do not lose your assigned temporary email address immediately. These are session cookies that do not track your activity across other websites. We do not use third-party tracking cookies that follow you around the internet. If you choose to disable cookies in your browser, the fundamental feature of maintaining a consistent email address during your session may not function correctly, but you will still be able to generate new addresses.
        </p>

        <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: '#333', marginTop: '30px', marginBottom: '10px' }}>
          Third-Party Privacy Policies
        </h3>
        <p style={{ marginBottom: '25px' }}>
          <strong>{CONFIG.siteName}</strong>'s Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites. We carefully select any potential partners to ensure they align with our values of user privacy, but we cannot control the data collection practices of external sites you may visit via links in the emails you receive.
        </p>

        <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: '#333', marginTop: '30px', marginBottom: '10px' }}>
          CCPA Privacy Rights (Do Not Sell My Personal Information)
        </h3>
        <p style={{ marginBottom: '25px' }}>
          Under the CCPA, among other rights, California consumers have the right to request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers. They also have the right to request that a business delete any personal data about the consumer that a business has collected. Furthermore, they have the right to request that a business that sells a consumer's personal data, not sell the consumer's personal data. If you make a request, we have one month to respond to you. However, since we do not store personal data like names, addresses, or phone numbers, and since we delete email data automatically, we effectively comply with the "deletion" requirement by default. We do not sell your data to anyone.
        </p>

        <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: '#333', marginTop: '30px', marginBottom: '10px' }}>
          GDPR Data Protection Rights
        </h3>
        <p style={{ marginBottom: '25px' }}>
          We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following. The right to access means you have the right to request copies of your personal data. The right to rectification means you have the right to request that we correct any information you believe is inaccurate. The right to erasure means you have the right to request that we erase your personal data, under certain conditions. The right to restrict processing means you have the right to request that we restrict the processing of your personal data. The right to object to processing means you have the right to object to our processing of your personal data. The right to data portability means you have the right to request that we transfer the data that we have collected to another organization, or directly to you. Given the ephemeral nature of <strong>{CONFIG.siteName}</strong>, most of this data is erased automatically before a request could even be processed, ensuring maximum privacy by design.
        </p>

        <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: '#333', marginTop: '30px', marginBottom: '10px' }}>
          Children's Information
        </h3>
        <p style={{ marginBottom: '25px' }}>
          Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity. <strong>{CONFIG.siteName}</strong> does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records. However, due to the anonymous nature of our service, we have no way of verifying the age of our users, which is why we advise parental supervision for all minors.
        </p>

        <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: '#333', marginTop: '30px', marginBottom: '10px' }}>
          Data Security Measures
        </h3>
        <p style={{ marginBottom: '25px' }}>
          We employ robust security measures to protect the limited data we handle. Our website is served exclusively over HTTPS (Hypertext Transfer Protocol Secure), which ensures that the communication between your browser and our servers is encrypted. This prevents eavesdroppers from intercepting the emails you view on our site. Our servers are protected by firewalls and intrusion detection systems. While no method of transmission over the Internet or method of electronic storage is 100% secure, we strive to use commercially acceptable means to protect your anonymity. The best security feature we offer is the automatic destruction of data, which eliminates the risk of data breaches by ensuring there is no data to breach.
        </p>

        <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: '#333', marginTop: '30px', marginBottom: '10px' }}>
          Changes to This Privacy Policy
        </h3>
        <p>
          We may update our Privacy Policy from time to time. Thus, we advise you to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately, after they are posted on this page. Your continued use of the service after any modifications to the Privacy Policy will constitute your acknowledgment of the modifications and your consent to abide and be bound by the modified Privacy Policy.
        </p>

      </div>
    </div>
  );
}
